#!/usr/bin/env python3
"""Import Telegram posts and build the static byplan blog."""

import argparse
import html
import json
import re
import shutil
import sys
import urllib.request
from urllib.parse import urlsplit
from datetime import datetime
from html.parser import HTMLParser
from pathlib import Path

CHANNEL = "byplandesign"
SITE = "https://byplan.ru"
ROOT = Path(__file__).resolve().parent.parent
UA = "Mozilla/5.0 (compatible; byplan-blog-import/1.0; +https://byplan.ru/)"
MARKER = "<!-- generated by scripts/blog-import.py; do not edit -->"
AUTHORS = {
    "zykova": "Наталья Зыкова, главный дизайнер byplan",
    "dinner": "Инесса Диннер, byplan",
    "team": "Команда byplan",
}
TRANSLIT = dict(zip("абвгдеёжзийклмнопрстуфхцчшщъыьэюя",
                    ("a", "b", "v", "g", "d", "e", "e", "zh", "z", "i", "y", "k", "l", "m", "n", "o", "p", "r", "s", "t", "u", "f", "h", "ts", "ch", "sh", "sch", "", "y", "", "e", "yu", "ya")))


def load_json(path):
    if not path.exists():
        return {}
    return json.loads(path.read_text(encoding="utf-8"))


def save_json(path, value):
    write_if_changed(path, json.dumps(value, ensure_ascii=False, indent=2,
                                      sort_keys=True) + "\n")


def write_if_changed(path, content):
    data = content.encode("utf-8")
    if path.exists() and path.read_bytes() == data:
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(data)


def strip_tags(value):
    value = re.sub(r"<br\s*/?\s*>", " ", value, flags=re.IGNORECASE)
    value = re.sub(r"<[^>]*>", "", value)
    return re.sub(r"\s+", " ", html.unescape(value).replace("\xa0", " ")).strip()


def parse_listing(source):
    posts = []
    for block in source.split("tgme_widget_message_wrap")[1:]:
        match = re.search(r'data-post=["\']byplandesign/(\d+)["\']', block)
        if not match:
            continue
        post_id = match.group(1)
        date_match = re.search(r'<time[^>]+datetime=["\']([^"\']+)', block)
        text_match = re.search(
            r'<div[^>]*class=["\'][^"\']*tgme_widget_message_text[^"\']*["\'][^>]*>(.*?)</div>\s*(?:<div|</div>)',
            block, re.S)
        photos = re.findall(
            r'tgme_widget_message_photo_wrap[^>]*style=["\'][^"\']*background-image:url\(["\']?([^"\')]+)',
            block, re.S)
        views_match = re.search(r'tgme_widget_message_views[^>]*>([^<]*)', block)
        posts.append({
            "id": post_id,
            "date": (date_match.group(1)[:10] if date_match else ""),
            "text_html": text_match.group(1).strip() if text_match else "",
            "photos": photos,
            "video": "tgme_widget_message_video" in block,
            "views": html.unescape(views_match.group(1).strip()) if views_match else "",
        })
    return posts


def fetch_channel():
    result = {}
    before = None
    for _ in range(40):
        url = f"https://t.me/s/{CHANNEL}" + (f"?before={before}" if before else "")
        request = urllib.request.Request(url, headers={"User-Agent": UA})
        with urllib.request.urlopen(request, timeout=30) as response:
            posts = parse_listing(response.read().decode("utf-8"))
        added = 0
        for post in posts:
            if post["id"] not in result:
                result[post["id"]] = {key: value for key, value in post.items() if key != "id"}
                added += 1
        if not posts or not added:
            break
        before = min(int(post["id"]) for post in posts)
    return result


def is_candidate(post):
    text = strip_tags(post.get("text_html", "")).lower()
    first_200, first_300 = text[:200], text[:300]
    case = (("было" in first_200 and "стало" in first_200) or
            any(term in first_200 for term in ("до и после", "до → после", "кейс")))
    excluded = any(term in text for term in
                   ("вдохновля", "насмотренност", "образовательная среда"))
    return "зыков" in first_300 or case or (len(text.split()) >= 250 and not excluded)


def ensure_stubs(titles, channel):
    for post_id, post in channel.items():
        if post_id in titles or not is_candidate(post):
            continue
        text = strip_tags(post.get("text_html", "")).strip()
        bold = re.search(r"<b[^>]*>(.*?)</b>", post.get("text_html", ""), re.S)
        draft = strip_tags(bold.group(1)).strip() if bold else re.split(r"[.!?\n]", text)[0].strip()
        titles[post_id] = {"title": "", "draft_title": draft[:160],
                           "words": len(text.split()), "photos": len(post.get("photos", [])),
                           "date": post.get("date", "")}


def make_slug(title):
    value = "".join(TRANSLIT.get(char, char) for char in title.lower())
    value = re.sub(r"[^a-z0-9]+", "-", value).strip("-")
    if len(value) <= 70:
        return value
    cut = value[:71].rfind("-")
    return value[:cut if cut > 0 else 70].rstrip("-")


class Sanitizer(HTMLParser):
    def __init__(self):
        super().__init__(convert_charrefs=True)
        self.output = []
        self.anchor_stack = []

    def handle_starttag(self, tag, attrs):
        if tag in ("b", "i"):
            self.output.append(f"<{tag}>")
        elif tag == "a":
            href = dict(attrs).get("href", "")
            emit = bool(href) and not href.startswith(("?", "/")) and urlsplit(href).scheme in ("http", "https")
            self.anchor_stack.append(emit)
            if emit:
                self.output.append(f'<a href="{html.escape(href, quote=True)}" rel="nofollow noopener" target="_blank">')

    def handle_endtag(self, tag):
        if tag in ("b", "i"):
            self.output.append(f"</{tag}>")
        elif tag == "a" and self.anchor_stack:
            if self.anchor_stack.pop():
                self.output.append("</a>")

    def handle_data(self, data):
        self.output.append(html.escape(data))


def html_to_blocks(text_html, lead_skip=0):
    value = re.sub(r'<i\s+class=["\']emoji["\'][^>]*>.*?<b[^>]*>(.*?)</b>.*?</i>', r"\1", text_html, flags=re.S)
    value = re.sub(r"<br\s*/?>", "\n", value, flags=re.I)
    paragraphs = re.split(r"\n\s*\n", value)
    remaining = int(lead_skip or 0)
    blocks = []
    for paragraph in paragraphs:
        lines = [line for line in paragraph.split("\n") if strip_tags(line).strip()]
        if remaining:
            removed = min(remaining, len(lines))
            lines, remaining = lines[removed:], remaining - removed
        if not lines:
            continue
        paragraph = "\n".join(lines)
        heading = re.fullmatch(r"\s*<b[^>]*>(.*?)</b>\s*", paragraph, re.S)
        parser = Sanitizer()
        parser.feed(heading.group(1) if heading and len(strip_tags(heading.group(1))) <= 90 else paragraph)
        inner = "".join(parser.output).strip().replace("\n", "<br>")
        if inner:
            blocks.append(("h2" if heading and len(strip_tags(heading.group(1))) <= 90 else "p", inner))
    return blocks


def plain_text(blocks):
    return " ".join(strip_tags(inner) for _, inner in blocks)


def download_images(post, post_id):
    paths = []
    for number, url in enumerate(post.get("photos", []), 1):
        relative = Path("assets/blog") / f"{post_id}-{number}.jpg"
        target = ROOT / relative
        paths.append("/" + relative.as_posix())
        if target.exists() and target.stat().st_size > 0:
            continue
        target.parent.mkdir(parents=True, exist_ok=True)
        request = urllib.request.Request(url, headers={"User-Agent": UA})
        with urllib.request.urlopen(request, timeout=30) as response:
            target.write_bytes(response.read())
    return paths


def read_site_bits():
    source = (ROOT / "index.html").read_text(encoding="utf-8")
    metrika = re.search(r"<!-- Yandex\.Metrika counter -->.*?<!-- /Yandex\.Metrika counter -->", source, re.S)
    version = re.search(r"bundle\.css\?v=(\d+)", source)
    if not metrika:
        raise SystemExit("Yandex.Metrika block is missing from index.html")
    if not version:
        raise SystemExit("bundle.css version is missing from index.html")
    return metrika.group(0), version.group(1)


def page_header(version):
    logo = "/assets/img/logo/byplan-logo.svg" if (ROOT / "assets/img/logo/byplan-logo.svg").exists() else "/assets/img/logo/byplan-logo.png"
    return f'''<header class="blog-header"><a href="/"><img src="{logo}" alt="byplan"></a><nav><a href="/#pricing">Тарифы</a><a href="/#cases">Кейсы</a><a href="/blog/">Блог</a><a class="btn btn--primary" href="/#anketa">Заполнить анкету</a></nav></header>'''


def document(head, body, bits):
    metrika, version = bits
    return f'''{MARKER}
<!DOCTYPE html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">{head}<link rel="stylesheet" href="/assets/css/bundle.css?v={version}"><link rel="stylesheet" href="/blog/blog.css">{metrika}</head><body>{page_header(version)}<main>{body}</main></body></html>
'''


def render_article(entry, post, imgs, bits, post_id, entries):
    title = html.escape(entry["title"])
    description = html.escape(entry.get("description", ""), quote=True)
    slug = entry["slug"]
    canonical = f"{SITE}/blog/{slug}/"
    image = (SITE + imgs[0]) if imgs else (f"{SITE}/assets/img/hero/hero-bg.jpg" if (ROOT / "assets/img/hero/hero-bg.jpg").exists() else "")
    image_meta = f'<meta property="og:image" content="{html.escape(image, quote=True)}">' if image else ""
    author = AUTHORS.get(entry.get("author", "team"), AUTHORS["team"])
    ld = {"@context": "https://schema.org", "@type": "BlogPosting", "headline": entry["title"],
          "datePublished": post["date"], "author": {"@type": "Person", "name": author},
          "mainEntityOfPage": canonical, "publisher": {"@type": "Organization", "name": "byplan"}}
    if image:
        ld["image"] = image
    head = f'''<title>{title} — byplan</title><meta name="description" content="{description}"><link rel="canonical" href="{canonical}"><meta property="og:type" content="article"><meta property="og:title" content="{title}"><meta property="og:description" content="{description}"><meta property="og:url" content="{canonical}">{image_meta}<script type="application/ld+json">{json.dumps(ld, ensure_ascii=False).replace("</", "<\\/")}</script>'''
    blocks = html_to_blocks(post.get("text_html", ""), entry.get("lead_skip", 0))
    for append_id in entry.get("append", []):
        appended = load_json(ROOT / "data/blog/channel.json").get(str(append_id), {})
        blocks.extend(html_to_blocks(appended.get("text_html", ""), 0))
    content = "".join(f"<{kind}>{inner}</{kind}>" for kind, inner in blocks)
    figures = "".join(f'<figure><img loading="lazy" src="{src}" alt="{title}"></figure>' for src in imgs)
    shown_date = datetime.strptime(post["date"], "%Y-%m-%d").strftime("%d.%m.%Y")
    others = [item for item in entries if item[0] != post_id]
    same_author = [item for item in others if item[1].get("author", "team") == entry.get("author", "team")]
    remaining = [item for item in others if item not in same_author]
    related_items = (same_author + remaining)[:3]
    related_links = "".join(
        f'<li><a href="/blog/{item[1]["slug"]}/">{html.escape(item[1]["title"])}</a> '
        f'<span class="blog-related-date">{datetime.strptime(item[2]["date"], "%Y-%m-%d").strftime("%d.%m.%Y")}</span></li>'
        for item in related_items)
    related = f'<section class="blog-related"><h2>Читайте также</h2><ul>{related_links}</ul></section>'
    body = f'''<article class="blog-article"><h1>{title}</h1><div class="blog-meta"><span>{html.escape(author)}</span><time datetime="{post["date"]}">{shown_date}</time></div>{content}{figures}{related}<aside class="blog-cta"><h2>Хотите такую планировку?</h2><a class="btn btn--primary" href="https://byplan.ru/#anketa">Заполнить анкету</a><a class="btn btn--ghost" href="https://t.me/byplandesign">Написать в Telegram</a></aside><p class="blog-source">Источник: <a href="https://t.me/byplandesign/{post_id}">пост в Telegram-канале byplan</a></p><footer><a href="/blog/">← Все статьи</a><a href="/">На главную</a></footer></article>'''
    return document(head, body, bits)


def render_index(entries, bits):
    description = "Статьи byplan о планировке квартир, дизайне и реализованных проектах."
    index_title = "Блог byplan — статьи о планировке квартир"
    newest_image = next((SITE + imgs[0] for _, _, _, imgs in entries if imgs), "")
    image_meta = f'<meta property="og:image" content="{html.escape(newest_image, quote=True)}">' if newest_image else ""
    head = f'''<title>{index_title}</title><meta name="description" content="{description}"><link rel="canonical" href="{SITE}/blog/"><meta property="og:title" content="{index_title}"><meta property="og:type" content="website"><meta property="og:url" content="{SITE}/blog/">{image_meta}'''
    cards = []
    for post_id, entry, post, imgs in entries:
        title = html.escape(entry["title"])
        excerpt = html.escape(plain_text(html_to_blocks(post.get("text_html", ""), entry.get("lead_skip", 0)))[:160])
        thumb = f'<a href="/blog/{entry["slug"]}/"><img loading="lazy" src="{imgs[0]}" alt="{title}"></a>' if imgs else ""
        cards.append(f'''<article class="blog-card">{thumb}<div><time datetime="{post["date"]}">{datetime.strptime(post["date"], "%Y-%m-%d").strftime("%d.%m.%Y")}</time><h2><a href="/blog/{entry["slug"]}/">{title}</a></h2><p>{excerpt}</p></div></article>''')
    return document(head, f'<section class="blog-index"><h1>Блог byplan</h1><div class="blog-list">{"".join(cards)}</div></section>', bits)


def prune_stale(slugs):
    blog = ROOT / "blog"
    for directory in blog.iterdir():
        index = directory / "index.html"
        if directory.is_dir() and directory.name not in slugs and index.exists() and index.read_text(encoding="utf-8").startswith(MARKER):
            shutil.rmtree(directory)


def update_sitemap(entries):
    path = ROOT / "sitemap.xml"
    source = path.read_text(encoding="utf-8")
    source = re.sub(r"\s*<url>(?:(?!</url>).)*?</url>", lambda m: "" if "/blog/" in m.group(0) else m.group(0), source, flags=re.S)
    blocks = ['  <url>\n    <loc>https://byplan.ru/blog/</loc>\n    <changefreq>weekly</changefreq>\n    <priority>0.6</priority>\n  </url>']
    for _, entry, post, _ in entries:
        blocks.append(f'''  <url>\n    <loc>{SITE}/blog/{entry["slug"]}/</loc>\n    <lastmod>{post["date"]}</lastmod>\n    <changefreq>monthly</changefreq>\n    <priority>0.5</priority>\n  </url>''')
    write_if_changed(path, source.replace("</urlset>", "\n" + "\n".join(blocks) + "\n</urlset>"))


def published_entries(titles, channel):
    result = []
    for post_id, entry in titles.items():
        if not entry.get("title") or post_id not in channel:
            continue
        if not entry.get("slug"):
            entry["slug"] = make_slug(entry["title"])
        post = channel[post_id]
        if not post.get("date"):
            print(f"skip {post_id}: no date", file=sys.stderr)
            continue
        imgs = [f"/assets/blog/{post_id}-{n}.jpg" for n in range(1, len(post.get("photos", [])) + 1)] if entry.get("images", True) else []
        result.append((post_id, entry, post, imgs))
    return sorted(result, key=lambda item: (item[2].get("date", ""), int(item[0])), reverse=True)


def fetch():
    channel = fetch_channel()
    titles_path = ROOT / "data/blog/titles.json"
    titles = load_json(titles_path)
    ensure_stubs(titles, channel)
    save_json(ROOT / "data/blog/channel.json", channel)
    save_json(titles_path, titles)
    for post_id, entry, post, _ in published_entries(titles, channel):
        if entry.get("images", True):
            download_images(post, post_id)


def build():
    channel = load_json(ROOT / "data/blog/channel.json")
    titles_path = ROOT / "data/blog/titles.json"
    titles = load_json(titles_path)
    entries = published_entries(titles, channel)
    save_json(titles_path, titles)
    bits = read_site_bits()
    for post_id, entry, post, imgs in entries:
        write_if_changed(ROOT / "blog" / entry["slug"] / "index.html",
                         render_article(entry, post, imgs, bits, post_id, entries))
    write_if_changed(ROOT / "blog/index.html", render_index(entries, bits))
    prune_stale({entry["slug"] for _, entry, _, _ in entries})
    update_sitemap(entries)


def main():
    parser = argparse.ArgumentParser(description="Import and build the byplan blog")
    parser.add_argument("command", choices=("fetch", "build", "all"))
    args = parser.parse_args()
    if args.command in ("fetch", "all"):
        fetch()
    if args.command in ("build", "all"):
        build()


if __name__ == "__main__":
    main()
